### ISSUE TITLE
Write Speed Limit Code

### ISSUE THREAD

**Issue by cpmarsh** [umigv/atlas#131]
The 5 mph speed limit, according to the IGV coordinators, can be implemented with a microcontroller. Since this is much easier than an analog/digital circuitry solution, we will be going with this approach. The code will be put in the 'safety' repository in the Github

**Comment by MishFTW** [comment]
Needs to be tested on the actual encoder

**Comment by MishFTW** [comment]
Done, needs to be tested on Tele-op bot
