### ISSUE TITLE
IMU Dewiggler

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/atlas#135]
The IMU data output from transform_imu wiggles around. Write an exponential mean filter to take sensor_msgs/Imu input, take the exponential average of the orientation, then output a filtered sensor_msgs/Imu.

**Comment by Gregory-Meyer** [comment]
Work abandoned, taking responsibility for this now

**Comment by kushalj1997** [comment]
This is resolved - the IMU wiggle was an illusion of oscillation of the gyro data above and below zero. When the IMU is transformed, we see the oscillation of the axis in the Y component of the transformed data also, and I've confirmed this same oscillation appears by showing that the non-transformed data also exhibits this wiggle. Looking at the data side by side, the transformed data corresponds to the raw data from the gyroscope, so there is no issue with the code either.
