### ISSUE TITLE
Polish/Complete Frame CAD

### ISSUE THREAD

**Issue by MishFTW** [umigv/atlas#156]
Brackets, holes, types of screw placed in appropriate locations
Placement of gearboxes figured out
Ready to export drawings for manufacturing service
Put frame related CAD into new folder; improved workflow

**Comment by yomn61** [comment]
Add Ramiro to Zenhub

**Comment by yomn61** [comment]
-Chain Tensioners for all gearboxes
-Double nut bolts to help not backing out
-
