### ISSUE TITLE
GPS Output

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/atlas#164]
Use the output from IMU/Encoder Odometry as an input to robot_localization's navsat_transform_node. NavSatFix data should be provided by nmea_navsat_driver connected to the SparkFun GPS, IMU data should be provided by the Phidgets IMU, and Encoder data should be from the Phidgets wheel encoders.

**Comment by MishFTW** [comment]
IMU was not incorrect reference frame and needs to be fixed;

**Comment by Gregory-Meyer** [comment]
this should be a turnkey solution using goat_launch:

roslaunch goat_launch gps.launch port:=/dev/ttyUSB<whatever>

**Comment by Gregory-Meyer** [comment]
tested outside, output pose was centered at (0, 0)
