### ISSUE TITLE
Finalize combined e-stop circuit

### ISSUE THREAD

**Issue by MishFTW** [umigv/atlas#168]
* Design a circuit for combined e-stop functionality
* Successful completion ensures vehicle stop if either wired or wireless e-stop is activated

**Comment by gtheller** [comment]
Wiring of wired e-stop should still be complete, status of wireless module is unknown. Roboclaws must be configured to take a non-latching stop signal. As far as I know, Greg knows how to do that. I'll consult him about how to configure them. If both e-stops are already mounted, confirming that they work should take about an hour.
