### ISSUE TITLE
Calculate gear ratio

### ISSUE THREAD

**Issue by MishFTW** [umigv/atlas#173]
* Competition platform gear ratio
* Calculate the proper ratio based on given information for CIM motor, AmpFlow motors

**Comment by yomn61** [comment]
What was the calculated gear ratio that we wanted to achieve?

**Comment by castroda** [comment]
About 30:1 for the 12v motor.

**Comment by yomn61** [comment]
How much for the AmpFlow 24V?

**Comment by castroda** [comment]
About 24:1.
