### ISSUE TITLE
Set up development NUC

### ISSUE THREAD

**Issue by MishFTW** [umigv/atlas#174]
Our current workflow is horseshit and depends a lot on the laptop. Team members rely on using their personal computers and we fall short. 

We need to set up 1 NUC for **production** on the robot that will be readily deployed, and one NUC for development purposes. Environment should be set up either via scripts or continuous integration (maybe later) and simply use Github to pull the latest software.

**Comment by cpmarsh** [comment]
Nico has now put SSH capability onto the NUC

**Comment by MishFTW** [comment]
http://atlas.umigv.com/atlas/ssh-access

**Comment by andreseg9726** [comment]
We downloaded the following on the nuc:
*movebase node and parameter files
*simulation node
*hector plugins for gazebo
*turtlebot teleop
