### ISSUE TITLE
Water Jetting DXF

### ISSUE THREAD

**Issue by yomn61** [umigv/atlas#177]
-Use the Drawing/CAD file of the flat bracket (ask Cameron or Ramiro if unsure) on fusion to create a DXF that can be used by the water jetting people in the ME shop
-We will need 25 brackets
-Try to make the DXF to fit in 16"x18", if not break up into two sheets

**Comment by MishFTW** [comment]
Fit 19 pieces on 12x12 aluminum sheet

**Comment by yomn61** [comment]
Could you make another smaller sheet with around 6 pieces as well?

**Comment by MishFTW** [comment]
I need clarification on what sheet size we are getting @yomn61 
I can alternatively make 2 sets of 12x12 and 1 set of 18x16

**Comment by yomn61** [comment]
Sent an email to Toby ask which would be preferred from his end, will update soon

**Comment by yomn61** [comment]
12"x12" pieces
