### ISSUE TITLE
GPS Text File Input

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/atlas#212]
We need a way to create dummy NavSatFix messages with which to navigate based on. This node should take in a rosparam argument "~file", read the file, and then set up a series of waypoints to navigate on. When we reach one waypoint, this node has no way of knowing, so we should send it an empty action to signal that it is time to start broadcasting the next waypoint.

**Comment by samjhall** [comment]
The purpose of this node is the same as that of Issue #138, so this issue was closed to avoid duplicating work.
