### ISSUE TITLE
Camera CV Guidance

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/atlas#213]
Since the accuracy of GPS is nominally about 15m, our camera must be used for the rest of the way to navigate to a waypoint barrel. This node should combine a multitude of inputs - vehicle odometry, the dummy GPS goal, and camera inputs (depth / rgb) - to output a MoveBase goal action.

**Comment by ramicaza** [comment]
The spec doesn't describe what waypoints look like so this is impossible lol
