### ISSUE TITLE
Atlas - Software Stack ENGR Documentation

### ISSUE THREAD

**Issue by MishFTW** [umigv/atlas#220]
http://atlas.umigv.com/atlas/software-stack

Provide a brief overview of every single ROS node:
* Data input
* Data output
* Purpose
* Modifications
* Link to wiki/material

**Comment by Gregory-Meyer** [comment]
Completed documentation for IMU and GPS nodes

**Comment by Gregory-Meyer** [comment]
Wrote up documentation for lidar nodes

**Comment by Gregory-Meyer** [comment]
Finished up documentation for all odometry and mapping nodes, TBD: teleoperation and state publishing nodes

**Comment by MishFTW** [comment]
I can do the remaining ones
