### ISSUE TITLE
Power wiring of competition bot

### ISSUE THREAD

**Issue by cpmarsh** [umigv/atlas#225]
This task will be done after the new platform is mechanically assembled, hopefully by 3/28, and completed before the weekly standup on 4/1

All wires needed for competition are in place, wires are properly soldered/tinned and cut to length for neatness. Once this is done, the robot will have a single on/off switch that can be thrown to turn it on. 

By mechanically assembled, we mean that that the robot platform is such that every needed component has a place and can be properly mounted.

**Comment by MishFTW** [comment]
Will this still get done before the standup tomorrow @ 3pm?

**Comment by MishFTW** [comment]
Not done because of broken Sabertooth controller, cannot send signals to motors.
