### ISSUE TITLE
Test Old CIM Motors

### ISSUE THREAD

**Issue by camkab** [umigv/atlas#226]
Verify that old CIM motors can be powered on

Measure the RPM of motors and monitor with oscilloscope to ensure consistency with the given charts

**Comment by MishFTW** [comment]
They work!

**Comment by yomn61** [comment]
Will do some load testing and see if they are up to spec

**Comment by yomn61** [comment]
Pushing this task back a milestone because of the lower priority that they entail given that they are back up motors

**Comment by yomn61** [comment]
Pushing back again for the same reason as before, will pursue after tele-op is perfectly done

**Comment by yomn61** [comment]
not necessary
