### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by kushalj1997** [umigv/atlas#230]
Allow remote builds of the software that you write, so that builds are consistent.
Steps:
- set up the Jetson to be accessed over the internet
- set up one remote build to run from a GitHub hook triggered from a push on a personal laptop
- set up standardized way to build projects
- write documentation on how to run remote builds

@cedricIGV move this to Week 14

**Comment by kushalj1997** [comment]
Please move this issue to week 15

**Comment by MishFTW** [comment]
What's the reason for pushing back issue twice now? Any particular roadblocks?

**Comment by MishFTW** [comment]
Moving to backlog for post comp review
