### ISSUE TITLE
Design and CAD Under Carriage Gearbox Mud Shield 

### ISSUE THREAD

**Issue by camkab** [umigv/atlas#231]
The current gearbox design will have the bottom of gearbox unprotected from any mud, dirt, etc and will need a housing to protect it underneath.  Design a 3D printable enclosure that can be attached to the undercarriage to protect the protruding gear.
Consider: attachment points, ground clearance, gear protrusion, base plate area of coverage near gearbox, etc) 
CAD design due by 3/25.

**Comment by MishFTW** [comment]
Ramiro worked on this

**Comment by Racalder** [comment]
Currently working on Version 2 of the CAD model, which will be slimmer and more compact than V1.
