### ISSUE TITLE
3D Print Gearbox Mud Shield

### ISSUE THREAD

**Issue by camkab** [umigv/atlas#248]
Once the current mud shield design has been reviewed and cleared, locate source to 3D print two pieces (mirrored) and print them. Consider printing spares. Attach to robot

**Comment by camkab** [comment]
Pieces are being printed right now in the Dude 3D lab. One piece is approximated for 20-ish hours if I recall correctly.

**Comment by yomn61** [comment]
One printed, other being printed, issue with bolt that runs into the mud shield

**Comment by yomn61** [comment]
Another 95% done Mud Shield is done printing, a spare for the that mud shield is printing now
