### ISSUE TITLE
Buy a Bigger USB Hub

### ISSUE THREAD

**Issue by yomn61** [umigv/atlas#253]
Our current USB Hub has only 4 inputs and we need one that can handle at least 6. 

We need to buy...

A USB Hub with 6 inputs 
OR
an extra USB Hub with at least 2 inputs if the Jetson can take another USB input.

 Ask Greg for the necessary timeline for this.

**Comment by Gregory-Meyer** [comment]
This board runs directly off of 12V (so we can run it from the batteries) and has seven ports:

http://a.co/2CpgjkI

**Comment by Gregory-Meyer** [comment]
@yomn61 purchased the intended USB hub
