### ISSUE TITLE
Determine if Current Sensors Box will be Big Enough

### ISSUE THREAD

**Issue by yomn61** [umigv/atlas#257]
Find all the CAD for the components outlined in https://docs.google.com/document/d/1icsIJlkS4UcNSqhZBfEX8AMNHSYCxMJbg_eqRXf92PQ/edit?usp=sharing for the Sensors Box
Then place the components in CAD and see if they will fit. Make sure the components are given room for their specific connectors (ie USB cords).
Report Findings
If not big enough, please find a box that will be big enough.

**Comment by MishFTW** [comment]
Purchased a bigger enclosure, @yomn61 ordered it via Amazon
