### ISSUE TITLE
Create a CAD Model of the LiDar Support

### ISSUE THREAD

**Issue by yomn61** [umigv/atlas#274]
Create a CAD Model of the LiDar Support to offset the LiDar off the top of the Sensors box with an "umbrella" and a way to route cables into the box from both the LiDar and the ZED camera.
Make by 11:59 PM Thursday night for review by Platform and Sensors.

**Comment by MishFTW** [comment]
https://a360.co/2q61fAO

**Comment by yomn61** [comment]
is the hole big enough for a USB to fit through? It seems to be really close and the measurement on fusion says its ~0.6" when a USB connector with the casing is 0.62"
