### ISSUE TITLE
Settle on Testing Speed

### ISSUE THREAD

**Issue by andreseg9726** [umigv/atlas#278]
It is essential that our robot stays within speed limits (1mph - 5mph) for the competition. However, the fastest our robot drives, the worse move_base performs. We need to find a sweetspot such that we can determine that the minimum average speed is always met and move_base performs well.

This ticket will be closed once you can prove that:
*Your choice is the most efficient solution.
*The speed limit average will not fall below 1mph

**Comment by mattsara24** [comment]
Determining speed has become much more difficult than originally thought. Increasing speed slightly (1 to 2 times) causes robots path planning to freak out and act weird. Larger increases (2 to 4 times) causes total failure of basically all things to do with movebase. Currently on hold while we determine proper course of action.
