### ISSUE TITLE
Change observation sources to align with sensors

### ISSUE THREAD

**Issue by andreseg9726** [umigv/atlas#279]
As you can see, on costmap_common_params.yaml we set observation sources to gazebo. You could try using the documentation on Atlas to update this such that movebase reads the laserScan from the RpLidar and reads the pointCloud from the camera. 

This ticket will be closed when:
*You could expect move_base to subscribe to these sources (we can't really test it right away)
*You show your code to the rest of the teammates present

**Comment by AkshaySG14** [comment]
Changed observation sources to take in data from actual sensors, rather than Gazebo data. Specifically, the frame ID and topics of LaserScan and PointCloud were added to the costmap_common_params.yaml file in movebase. This would allow for movebase to work with the actual robot itself.
