### ISSUE TITLE
Create a Controls Launch file

### ISSUE THREAD

**Issue by andreseg9726** [umigv/atlas#280]
We could become more efficient if we could have a single launch file that could run the simulation.
Make a launch file that:
*Launches gazebo with our current world
*Runs gmapping with the current parameters
*Runs Rviz
*Runs movebase
In the order mentioned before.
You can achieve this in different ways and I won't care that much the way you choose as long as it works.

**Comment by abschmidt6** [comment]
./run_all.sh was updated to coordinate with ./run_gmapping.sh. All 'sudo' commands were removed from ./run_gmapping.sh.

./run_all.sh now correctly runs the simulation in its entirety.
