### ISSUE TITLE
Set up networking on other devices

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/atlas#291]
umigv-nuc1, umigv-jetson0, and umigv-jetson1 need to have their networking set up, including modifying /etc/hosts, ~/.bashrc, and the wired network configuration.

Follow the guidelines as set here to properly configure the devices' network interfaces: http://atlas.umigv.com/networking

**Comment by jnnwa** [comment]
Jetson1 and laptop confirmed

**Comment by Gregory-Meyer** [comment]
Verified nuc1 after reinstalling Ubuntu 16.04. This was done a few days ago but not closed.
