### ISSUE TITLE
Design and 3d print battery brackets

### ISSUE THREAD

**Issue by camkab** [umigv/atlas#339]
Design brackets that will securely hold the battery in its new position while still allowing accessibility to pull the battery out. Mind where the bolts will hold the bracket so they don't interfere with support bars underneath.

3d print the brackets.

**Comment by camkab** [comment]
First set of printed brackets had few issues:
Printer failed and caused offset mid print, needing to reprint the brackets.
The key did not fit into the keyhole in the bracket, requiring a better tolerance to account for the printer's printing error.

**Comment by camkab** [comment]
All pieces should be done printing by now and ready to be picked up and installed.

**Comment by camkab** [comment]
Some changes to be made for future models, sticky notes defining the changes were handed to the owners of this task.

**Comment by karolinarak** [comment]
Changes were made on Autodesk files from the definitions on the sticky notes, brackets were printed as well
