### ISSUE TITLE
Move_Base Node

### ISSUE THREAD

**Issue by austone** [umigv/atlas#39]
This is a task primarily focused on setting up the first working node.  This task may not be integrated with the existing sensors; rather, it's for us to have a working system before integrating with our sensors data.

**Comment by andrewchouman** [comment]
Worked for a couple hours on Sunday. There are many errors that we don't know how to fix.

**Comment by andreseg9726** [comment]
It compiles and runs, it's just not doing what's supposed to.  I attached the graph for the current connections between nodes.![rosgraph.png](https://images.zenhubusercontent.com/59ed00c0a468affe6df7b082/d8dbfa14-8fb7-4252-9991-6d73966924fd)
