### ISSUE TITLE
Wired E-Stop implementation

### ISSUE THREAD

**Issue by cpmarsh** [umigv/atlas#74]
On the physical robot, the literal big red button will be placed. When pressed, all four of the relays connected to each of the motors will be disabled, and the robot will be physically incapable of moving. A latching Big Red Button will need to be ordered for this task to be finished.

**Comment by MishFTW** [comment]
Issue acceptance criteria needs to be updated @cpmarsh

**Comment by MishFTW** [comment]
Button works tested in various conditions
