### ISSUE TITLE
Create Demo motion Code

### ISSUE THREAD

**Issue by austone** [umigv/atlas#80]
For the Giving Blue Day demo, we want three simple paths that the vehicle can follow. Mish can be contacted for the dimensions of the demo space.

**Comment by MishFTW** [comment]
Done with circle pattern
Working with square
Issues with fwd/backward. Need to offset PWM, to take into account negative input ranges (can be software problem pref)

**Comment by MishFTW** [comment]
Fwd/back is done with Arduino/Sabertooth combo
