### ISSUE TITLE
Order HDMI & USB Drives for Embedded Systems

### ISSUE THREAD

**Issue by cpmarsh** [umigv/atlas#98]
3 HDMI cables (gold plated)
2 USB 3.0 drives > 16 gb 
2 SDHC or SDXC Cards > 16 gb

**Comment by Gregory-Meyer** [comment]
3x http://a.co/8qFXxnZ
3x http://a.co/3jqHSZv
2x http://a.co/2BF2mnt
2x http://a.co/9wH3FgC
